server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Required for React Router (Single Page Application fallback)
        try_files $uri $uri/ /index.html;
    }
}
